export const AUDIT_ACTIONS = {
  CLIENT_CREATED: "client.created",
  CLIENT_UPDATED: "client.updated",
  CLIENT_ARCHIVED: "client.archived",
  CLIENT_RESTORED: "client.restored",
  CLIENT_DELETED: "client.deleted",
  TEMPLATE_CREATED: "template.created",
  TEMPLATE_UPDATED: "template.updated",
  TEMPLATE_ARCHIVED: "template.archived",
  TEMPLATE_FIELDS_UPDATED: "template.fields_updated",
  FORM_REQUEST_CREATED: "form_request.created",
  FORM_REQUEST_CANCELLED: "form_request.cancelled",
  FORM_REQUEST_TOKEN_ROTATED: "form_request.token_rotated",
  FORM_REQUEST_OPENED: "form_request.opened",
  FORM_SESSION_STARTED: "form_session.started",
  FORM_DOCUMENT_SAVED: "form_document.saved",
  FORM_DOCUMENT_FILL_SUBMITTED: "form_document.fill_submitted",
  SIGNATURE_CREATED: "signature.created",
  ACCEPTANCE_RECORDED: "acceptance.recorded",
  FORM_DOCUMENT_FINALIZED: "form_document.finalized",
  ORGANIZATION_SIGNATURE_UPDATED: "organization.signature_updated",
  ORGANIZATION_EMAIL_TEMPLATE_UPDATED: "organization.email_template_updated",
  ORGANIZATION_EMAIL_TEMPLATE_RESET: "organization.email_template_reset",
} as const;

export const AUDIT_ENTITY_TYPES = {
  CLIENT: "client",
  DOCUMENT_TEMPLATE: "document_template",
  FORM_REQUEST: "form_request",
  FORM_DOCUMENT: "form_document",
  FORM_SESSION: "form_session",
  SIGNATURE: "signature",
  ACCEPTANCE: "acceptance",
  ORGANIZATION: "organization",
  ORGANIZATION_EMAIL_TEMPLATE: "organization_email_template",
} as const;
